---
name: Gate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rust-check:
    name: rust check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - id: tools
        run: rustup component add clippy rustfmt
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - id: check
        name: cargo check
        if: ${{ !cancelled() && steps.tools.conclusion == 'success' }}
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo test
        if: ${{ !cancelled() && steps.check.conclusion == 'success' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo clippy
        if: ${{ !cancelled() && steps.check.conclusion == 'success' }}
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
